# Generated by Django 6.0.2 on 2026-02-26 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('days', models.JSONField(default=list)),
                ('time', models.CharField(max_length=8)),
                ('feeding_amount_kg', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='iot.device')),
            ],
        ),
    ]
