# Generated by Django 6.0.2 on 2026-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Manila', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
