# Generated by Django 6.0.2 on 2026-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_alert_refresh_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
