# Generated by Django 6.0.2 on 2026-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_log_timestamp_from_esp32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
