# Generated by Django 6.0.2 on 2026-03-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_alter_log_timestamp'),
        ('iot', '0011_log_refresh_tracking'),
    ]

    operations = [
    ]
