# Generated by Django 6.0.3 on 2026-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_systemsettings_alert_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesensorstate',
            name='battery_adc_pin',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='devicesensorstate',
            name='battery_voltage_v',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
