# Generated by Copilot to remove redundant battery ADC pin storage from sensor state.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_devicesensorstate_battery_adc_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicesensorstate',
            name='battery_adc_pin',
        ),
    ]