# Generated by Django 6.0.3 on 2026-05-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0019_remove_devicesensorstate_battery_adc_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('boot_id', models.CharField(blank=True, default='', max_length=128)),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='esp32', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('delivery_status', models.CharField(default='accepted', max_length=32)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iot.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='iot_devicee_device__6fd2c6_idx'), models.Index(fields=['device', 'event_type', '-occurred_at'], name='iot_devicee_device__501b3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'event_id'), name='uniq_device_event_id')],
            },
        ),
    ]
