# Generated by Django 6.0.3 on 2026-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0020_deviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
