# Generated by Django 6.0.3 on 2026-05-20 12:00

import iot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0026_update_grain_calibrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='grain_types',
            field=models.JSONField(default=iot.models.default_grain_types),
        ),
    ]
