# Generated by Django 6.0.3 on 2026-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0030_backfill_deviceconfig_grain_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesensorstate',
            name='feed_current_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesensorstate',
            name='feed_required_next_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesensorstate',
            name='feed_sufficient',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
