# Generated by Django 6.0.3 on 2026-06-10 05:59

from django.db import migrations, models


def collapse_restoration_alerts(apps, schema_editor):
    Alert = apps.get_model('iot', 'Alert')
    restoration_types = {
        'power_restored': 'power_outage',
        'device_connection_restored': 'device_connection_loss',
        'low_battery_shutdown_resolved': 'low_battery_shutdown',
    }

    for restored_type, trigger_type in restoration_types.items():
        restored_alerts = Alert.objects.filter(alert_type=restored_type).order_by('timestamp', 'id')
        for restored in restored_alerts:
            trigger = Alert.objects.filter(
                device_id=restored.device_id,
                alert_type=trigger_type,
                timestamp__lte=restored.timestamp,
            ).order_by('-timestamp', '-id').first()

            if trigger is None:
                restored.alert_type = trigger_type
                restored.resolved = True
                restored.resolved_at = restored.timestamp
                restored.save(update_fields=['alert_type', 'resolved', 'resolved_at'])
                continue

            payload = dict(trigger.payload or {})
            payload.update(dict(restored.payload or {}))
            payload.setdefault('resolved_at', restored.timestamp.isoformat())
            trigger.resolved = True
            trigger.resolved_at = restored.timestamp
            trigger.last_updated = restored.timestamp
            trigger.payload = payload
            trigger.save(update_fields=['resolved', 'resolved_at', 'last_updated', 'payload'])
            restored.delete()

    for alert in Alert.objects.filter(resolved=True, resolved_at__isnull=True):
        alert.resolved_at = alert.last_updated
        alert.save(update_fields=['resolved_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0031_devicesensorstate_feed_current_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(collapse_restoration_alerts, migrations.RunPython.noop),
    ]
