# Generated by Django 6.0.3 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0033_remove_keypad_calibration_from_device_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesensorstate',
            name='water_current_liters',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
